# Generated by Django 5.2.6 on 2026-09-07 07:13

import config.api.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("target_type", models.CharField(blank=True, max_length=60)),
                ("target_id", models.CharField(blank=True, max_length=60)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("outcome", models.CharField(default="success", max_length=20)),
                ("correlation", models.UUIDField(default=uuid.uuid4)),
                ("summary", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="CommissionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("closed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end__gte", models.F("start"))),
                        name="valid_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommissionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                (
                    "marketer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.commissionperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(db_index=True, default=config.api.models.today),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("comment", models.CharField(max_length=500)),
                ("potential", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("finalized", "Finalized"), ("archived", "Archived")],
                        db_index=True,
                        default="finalized",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "marketer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
                "permissions": [
                    ("view_all_marketing", "View All Marketing"),
                    ("manage_all_marketing", "Manage All Marketing"),
                    ("assign_marketer", "Assign Marketer"),
                    ("view_reports", "View Reports"),
                    ("view_all_reports", "View All Reports"),
                    ("export_reports", "Export Reports"),
                    ("manage_commissions", "Manage Commissions"),
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("target", models.PositiveBigIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=0)),
                ("complete", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenditureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("identity", models.CharField(max_length=160, unique=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("normalized_name", models.CharField(max_length=150)),
                ("source_name", models.CharField(blank=True, max_length=150)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("region", "Region"),
                            ("district", "District"),
                            ("ward", "Ward"),
                            ("street", "Street"),
                            ("local", "Local"),
                        ],
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(default="custom", max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("identity", models.CharField(max_length=400, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(db_index=True, default=config.api.models.today),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Mobile Money", "Mobile Money"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("receipt", models.FileField(blank=True, upload_to="receipts/%Y/%m")),
                (
                    "status",
                    models.CharField(
                        choices=[("recorded", "Recorded"), ("void", "Void")],
                        db_index=True,
                        default="recorded",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.customer",
                    ),
                ),
                (
                    "marketer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expenditure_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.expendituretype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.location",
            ),
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("token", models.UUIDField(primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=30)),
                ("result", models.PositiveBigIntegerField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("base", models.DecimalField(decimal_places=2, max_digits=18)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.commissionpolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("reuse_location", models.BooleanField(default=True)),
                ("columns", models.JSONField(default=dict)),
                (
                    "last_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.location",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(db_index=True, default=config.api.models.today),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("reference", models.CharField(max_length=60, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.customer",
                    ),
                ),
                (
                    "marketer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
                "permissions": [("confirm_sale", "Confirm and correct sales")],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="commissionpolicy",
            constraint=models.UniqueConstraint(
                fields=("marketer", "period"), name="one_policy"
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base__gte", 0), ("rate__gte", 0), ("rate__lte", 100)
                ),
                name="valid_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenditure",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="positive_expense"
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="positive_sale"
            ),
        ),
    ]
