# Generated by Django 5.2.17 on 2026-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_location_normalized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="target_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
