# Generated by Django 5.2.17 on 2026-09-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_draft_target_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionpolicy",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.commissionperiod"
            ),
        ),
        migrations.AlterField(
            model_name="policyrevision",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.commissionpolicy",
            ),
        ),
    ]
