# Generated by Django 5.2.17 on 2026-09-08 10:40

from django.db import migrations, models


def choose_default(apps, schema_editor):
    from django.utils import timezone
    Period = apps.get_model('api', 'CommissionPeriod')
    periods = Period.objects.using(schema_editor.connection.alias)
    if periods.filter(is_default=True).exists():
        return
    today = timezone.localdate()
    ordered = periods.order_by('-start', '-pk')
    selected = (ordered.filter(start__lte=today, end__gte=today).first()
                or ordered.filter(closed=False).first() or ordered.first())
    if selected:
        periods.filter(pk=selected.pk).update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_commissionpolicy_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionperiod",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(choose_default, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="commissionperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="one_default_commission_period",
            ),
        ),
    ]
