server {
    listen 80;
    listen [::]:80;
    server_name marketing.britishschool.ac.tz;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/marketing/acme;
    }
    location / {
        return 301 https://marketing.britishschool.ac.tz$request_uri;
    }
}
